### ISSUE TITLE
Firefox: Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by fregante** [juliangruber/browser-run#145]
Has anyone tried running tests on Travis in Firefox? It works correctly with Electron but with Firefox I get this error:

``` 
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^
Unexpected data: 
```

And if I add the `MOZ_HEADLESS=1` env as suggested by [Travis’s docs](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-firefox-addon-in-headless-mode), I get this:

```
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^
Unexpected data: *** You are running in headless mode.
``` 

This is my Travis config:

```yaml
language: node_js
node_js:
  - stable
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
```

Full failing Travis log: https://travis-ci.com/bfred-it/insert-text-textarea/builds/108077120

**Comment by bfred-it** [comment]
I think I found the problem: **any extra output by Firefox is interpreted as an error.**

This introduces two limitations:
- Firefox’ native headless mode can’t be used because it outputs `*** You are running in headless mode.`
- Firefox 66 (currently the latest) probably outputs something because it’s the only version that fails. 

My working configuration is:

```
language: node_js
node_js:
  - stable
addons:
  firefox: "65.0"
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
```
